apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-nosukero
resources:
  # template
  - ../../templates/minecraft-server
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-dbaddress.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-discordsrv.yaml
