apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haramis-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/maron-gt123/k8s-setup-for-proxmox.git
    targetRevision: main
    path: k8s/manifests/apps/haramis-mcserver
  syncPolicy:
    automated: {}
