apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # statefulset
  - ./statefulset.yaml
  - ./clusterip-service.yaml

  # jmx-exporter-config
  - ./config/jmx-exporter-mc-config.yaml
  - ./config/mc-paper-global.yaml
