apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-plugin-welcometext-configs
data:
  config.yml: |
    Config:
      # There are three modes to welcome guests:
      #   - ALWAYS: Always welcome
      #   - NOT_LOGGED_RECENTLY: If you have not logged in recently
      #   - ONCE: Only once
      mode: ALWAYS
      seconds-threshold: 600 # How many minutes must have passed since the last connection. Only for NOT_LOGGED_RECENTLY
    
      welcome-message: true
      particles: true
      
      TitleAndSubtitles:
        title: true
        titleText: "&aようこそはら民サーバーへ!"
        subtitle: true
        subtitleText: "&bはらみんと一緒に楽しみましょう"
        
      Sound:
        enabled: false
        sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  
  messages.yml: |
    Messages:
      message-welcome-text:
      - '&4&l はら民サブスクメンバー限定サーバーへようこそ'
      - '&e&l このサーバーでは以下のルールを守ってください'
      - '&e1. 他人に迷惑をかけない'
      - '&e2. 不正行為をしない'
      - '&e3. 迷惑行為・不正行為が発覚した場合は管理者からkick等の処置をいたします'
      - '&e4. 不具合発見時は同Discordメンバー内のmaron_iQSに連絡をお願いします'
      - '&b&l 各サーバーについて'
      - '&b S1：生活サーバー　S2以降：将来拡張用'
      - '&b 各サーバーに入るにはホログラム付近にあるゲートに近づいてください'
  
  particles.yml: |
    Particles:
      Particle: MOBSPAWNER_FLAMES
      Count: 7
      totalSeconds: 2
      intervalSeconds: 1
