apiVersion: v1
kind: ConfigMap
metadata:
  name: discordbot-config
data:
  config.yaml: |
    # =====================================
    # Discord Whitelist Bot Configuration
    # This file is a template.
    # Sensitive values must be supplied
    # via environment variables (CFG_*)
    # =====================================
    
    bot:
      token: ${CFG_BOT_TOKEN}
    
    server:
      apply_channel: ${CFG_SERVER_APPLY_CHANNEL}
      approve_channel: ${CFG_SERVER_APPROVE_CHANNEL}
      admin_role: ${CFG_SERVER_ADMIN_ROLE}
    
    minecraft:
      whitelist_file: "/app/whitelist.json"  # CFG_MINECRAFT_WHITELIST_FILE
      allowlist_file: "/app/allowlist.json"  # CFG_MINECRAFT_ALLOWLIST_FILE
    
    commands:
      bds_reload: ""      # CFG_COMMANDS_BDS_RELOAD
