apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
spec:
  template:
    spec:
      containers:
        - name: bot
          imagePullPolicy: Always
          env:
            - name: CFG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_BOTKEY
