apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
spec:
  template:
    spec:
      containers:
        - name: bot
          imagePullPolicy: Always
          env:
            - name: CFG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_BOTKEY
            - name: CFG_SERVER_APPLY_CHANNEL
              valueFrom:
                secretKeyRef: 
                  name: secret-discordbot
                  key: DISCORD_APPLY_CHANNELID
            - name: CFG_SERVER_APPROVE_CHANNEL
              valueFrom:
                secretKeyRef: 
                  name: secret-discordbot
                  key: DISCORD_APPROVE_CHANNELID
            - name: CFG_SERVER_ADMIN_ROLE
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_ROLEID
