apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
spec:
  template:
    spec:
      containers:
        - name: bot
          env:
            - name: CFG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: BOT_TOKEN
            - name: CFG_SERVER_APPLY_CHANNEL
            - name: CFG_SERVER_APPROVE_CHANNEL
