apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.37.0
          env:
            - name: WORLDEDIT_URL
              value: "https://hangarcdn.papermc.io/plugins/EngineHub/WorldEdit/versions/7.3.16/PAPER/worldedit-bukkit-7.3.16.jar"
            - name: WORLDGUARD_URL
              value: "https://cdn.modrinth.com/data/DKY9btbd/versions/PO4MKx7e/worldguard-bukkit-7.0.14-dist.jar"
            - name: BLUEMAP_URL
              value: "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.13/bluemap-5.13-paper.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/bluemap-paper.jar "${BLUEMAP_URL}"
      containers:
        - name: minecraft
          resources:
            requests:
              # pod リソース設定
              cpu: "2"
              memory: 4G
          env:
            # ---- 基本設定 ---- 
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 4G            
            # ---- server configの変数 ---- 
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: CFG_ALLOW_END
              value: "false"
            # ---- plugins configの変数 ---- 
            # ---- plugins datebase ---- 
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: disney
            # ---- discord SRV ---- 
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: CFG_CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
            - name: CFG_DISCORDSRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-disney
                  key: CFG_DISCORDSRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-disney
                  key: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
            # ------時間天候無効化コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
                /gamerule doMobSpawning false
                /gamerule spawn-npcs false
                /gamerule pvp false
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ worldedit ------
            - name: init-download-volume
              mountPath: /data/plugins/worldedit.jar
              subPath: worldedit.jar
            # ------ worldguard ------
            - name: init-download-volume
              mountPath: /data/plugins/worldguard.jar
              subPath: worldguard.jar
            # ------ bluemap ------
            - name: init-download-volume
              mountPath: /data/plugins/bluemap-paper.jar
              subPath: bluemap-paper.jar
            # ------plugins関連のマウント ------
            # worldのマウント
            - name: mc-plugin-bluemap-config
              mountPath: /config/plugins/BlueMap/maps
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-exp-disney-pvc
        # bluemap-worldデータの永続ストレージの指定
        - name: mc-plugin-bluemap-config
          configMap:
            name: mc-plugin-bluemap-config
