apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-uuidredirect-config
data:
  uuidredirect-config.json: |
    {
      "11111111-1111-1111-1111-111111111111": {
        "username": "ExamplePlayer",
        "server": "survival"
      },
      "": {
        "username": "NameOnlyPlayer",
        "server": "lobby"
      }
    }
