apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
data:
  jmx-exporter-config.yaml: |
    ---
    startDelaySeconds: 0
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    whitelistObjectNames: []
    blacklistObjectNames: []
    rules: []
