apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-nosukero
resources:
  # template
  - ../../templates/minecraft-default
  
  # secret
  - http://nas.mcnet/k8s/mc-nosukero/secret-mc-common.yaml
