apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      initContainers:
        # ------pluginsファイル生成関連------
        - name: plugins-download
          image: busybox:1.37.0
          env:
            - name: WORLDEDIT_URL
              value: "https://hangarcdn.papermc.io/plugins/EngineHub/WorldEdit/versions/7.3.16/PAPER/worldedit-bukkit-7.3.16.jar"
            - name: WORLDGUARD_URL
              value: "https://cdn.modrinth.com/data/DKY9btbd/versions/PO4MKx7e/worldguard-bukkit-7.0.14-dist.jar"
            - name: SERVERSPAWN_URL
              value: "https://cdn.modrinth.com/data/kfKmwtZp/versions/CuOWUqFJ/ServerSpawn.jar"
            - name: HOLOGRAMS_URL
              value: "https://github.com/DecentSoftware-eu/DecentHolograms/releases/download/2.9.8/DecentHolograms-2.9.8.jar"
          volumeMounts:
            - name: init-download-volume
              mountPath: /root/initContainer-download
          command:
            - sh
            - -c
            - >
              wget -O /root/initContainer-download/worldedit.jar "${WORLDEDIT_URL}" &&
              wget -O /root/initContainer-download/worldguard.jar "${WORLDGUARD_URL}" &&
              wget -O /root/initContainer-download/ServerSpawn.jar "${SERVERSPAWN_URL}" &&
              wget -O /root/initContainer-download/DecentHolograms.jar "${HOLOGRAMS_URL}"
      containers:
        - name: minecraft
          env:
            # ---- server configの変数 ---- 
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: CFG_ALLOW_END
              value: "false"
            # ---- plugins configの変数 ---- 
            # ---- discord SRV ---- 
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: lobby
            - name: CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
            - name: CFG_DISCORDSRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-lobby
                  key: CFG_DISCORDSRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-lobby
                  key: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
            # ------
            # 603990：Welcome Text
            - name: SPIGET_RESOURCES
              value: "101403"
            # ------時間天候無効化コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
                /gamerule doMobSpawning false
                /gamerule spawn-npcs false
                /gamerule pvp false
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
            # ------ world-backupデータ ------
            - name: world-data-backup
              mountPath: /data/Backups
            # ------initでダウンロードしたプラグインをマウント ------
            # ------ worldedit ------
            - name: init-download-volume
              mountPath: /data/plugins/worldedit.jar
              subPath: worldedit.jar
            # ------ worldguard ------
            - name: init-download-volume
              mountPath: /data/plugins/worldguard.jar
              subPath: worldguard.jar
            # ------ ServerSpawn ------
            - name: init-download-volume
              mountPath: /data/plugins/ServerSpawn.jar
              subPath: ServerSpawn.jar
            # ------ DecentHolograms ------
            - name: init-download-volume
              mountPath: /data/plugins/DecentHolograms.jar
              subPath: DecentHolograms.jar
            # ------ holograms-Gateways ------
            - name: mc-plugin-holograms-config
              mountPath: /config/plugins/DecentHolograms/holograms
            # ------ serverspawn ------
            - name: mc-plugin-serverspawn-config
              mountPath: /config/plugins/ServerSpawn/ServerSpawn.yml
              subPath: ServerSpawn.yml
            - name: mc-plugin-serverspawn-config
              mountPath: /config/plugins/ServerSpawn/Messages.yml
              subPath: Messages.yml
            # ------ worldgard-regions ------
            - name: mc-plugin-worldgard-regions-config
              mountPath: /config/plugins/WorldGuard/worlds/world/regions.yml
              subPath: regions.yml
            # ------　welcome texit ------
            - name: mc-plugin-welcometext-config
              mountPath: /config/plugins/WelcomeText
            # ------　advancedportals-destinations ------
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/desti/S1-world.yaml
              subPath: s1-world-destinations.yml
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/desti/S2-world.yaml
              subPath: s2-world-destinations.yml
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/desti/disney-world.yaml
              subPath: disney-world-destinations.yml
            # ------　advancedportals-portals ------
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/portals/S1-world.yaml
              subPath: s1-world-portals.yml
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/portals/S2-world.yaml
              subPath: s2-world-portals.yml
            - name: mc-plugin-advancedportals-configs
              mountPath: /config/plugins/AdvancedPortals/portals/disney-world.yaml
              subPath: disney-world-portals.yml
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-lobby-pvc
        # world-backupデータの永続ストレージの指定
        - name: world-data-backup
          persistentVolumeClaim:
            claimName: haramis-lobby-backup-pvc
        # holograms-configmap格納先
        - name: mc-plugin-holograms-config
          configMap:
            name: mc-plugin-holograms-configs
        # serverspawn-configmap格納先
        - name: mc-plugin-serverspawn-config
          configMap:
            name: mc-plugin-serverspawn-config
        # worldgard-regions-configmap格納先
        - name: mc-plugin-worldgard-regions-config
          configMap:
            name: mc-plugin-worldgard-regions-config
        # welcome texit configmap格納先
        - name: mc-plugin-welcometext-config
          configMap:
            name: mc-plugin-welcometext-configs
