apiVersion: v1
kind: PersistentVolume
metadata:
  name: bedrock-worlds-pv
  labels:
    app: bedrock-worlds-pv
spec:
  storageClassName: bedrock-worlds-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.6.140
    path: /kubanetesu-NFS/minecraft/haramis_s1/
  persistentVolumeReclaimPolicy: Retain
