apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bedrock-whitelists-pvc
  labels:
    app: bedrock-whitelists-pvc
spec:
  storageClassName: mc-bedrock-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
