apiVersion: v1
kind: Service
metadata:
  name: bedrock-ib
  labels:
    app: mc-bedrock
spec:
  type: LoadBalancer
  ports:
    - name: bedrock-service
      port: 19132
      protocol: UDP
      targetPort: bedrock-service
  selector:
    app: mc-bedrock
  loadBalancerIP: 172.1.0.0
