apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-bedrock
  labels:
    app: mc-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-bedrock
  template:
    metadata:
      labels:
        app: mc-bedrock
    spec:
      containers:
        - name: mc-bedrock
          image: itzg/minecraft-bedrock-server
          resources:
            requests:
              # pod リソース設定
              cpu: "2"
              memory: 2G
          command:
            - /bin/sh
            - -c
            - |
              mkfifo /tmp/bedrock.stdin
              cat /tmp/bedrock.stdin | /usr/local/bin/start-bedrock.sh

          env:
            # ---- 基本設定 ---- 
            - name: TZ
              value: Asia/Tokyo
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "LATEST"
            - name: GAMEMODE
              value: survival
            - name: DIFFICULTY
              value: normal
          ports:
            - name: bedrock-service
              containerPort: 19132
              protocol: UDP
          volumeMounts:
            - name: world-data
              mountPath: /data/worlds/Bedrock level
            - name: whitelists-data
              mountPath: /data/allowlist.json
              subPath: allowlist.json
            - name: bedrock-tmp
              mountPath: /tmp
    
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: bedrock-world-pvc
        # whitelistの申請用と承認用データの永続ストレージの指定
        - name: whitelists-data
          persistentVolumeClaim:
            claimName: bedrock-whitelists-pvc
        - name: bedrock-tmp
          emptyDir: {}
