apiVersion: v1
kind: ConfigMap
metadata:
  name: access-config
data:
  config.yml: |
    # =====================
    # TikTok settings
    # =====================
    tiktok:
      # TikTok Live streamer username (without @)
      user: nosu_kero_kero

    # =====================
    # HTTP forward settings
    # =====================
    http:
      # HTTP endpoint to which events are forwarded
      endpoint: "http://jamming-service:8080/event"
      # Timeout for HTTP requests (in seconds)
      timeout: 5

    # =====================
    # Like counter settings
    # =====================
    # Interval to reset per-user LIKE totals (seconds)
    #Example:
    #   60        = 1 minute
    #   3600     = 1 hour
    #   86400    = 24 hours
    reset_interval_seconds: 3600
