apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-live-runner
spec:
  template:
    spec:
      containers:
        - name: tiktok-live-runner
          env:
            - name: TZ
              value: Asia/Tokyo
