apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-live
spec:
  template:
    spec:
      containers:
        - name: tiktok-live
          image: marongt123/tiktok-live-mc-event-runner:dummy
