apiVersion: v1
kind: ConfigMap
metadata:
  name: rcon-login-script
data:
  rcon-login-template.sh: |
    #!/bin/bash
    # 自動ログイン用 RCON スクリプト

    RCON_HOST="[service_name].[namespace].svc.cluster.local"
    RCON_PORT="25575"
    RCON_PASS=123456789

    /usr/local/bin/rcon-cli \
      --host $RCON_HOST \
      --port $RCON_PORT \
      --password $RCON_PASS \
      --interactive
