apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis-disney
resources:
  # template
  - ../../templates/minecraft-server
  # pv & pvc
  - ./pv-haramis-exp-disney.yaml
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-dbaddress.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-discordsrv.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-disney.yaml
  
  # config
  - ./config/mc-plugin-bluemap-worlds-config.yaml
patches:
  - path: statefulset-haramis-exp-disney.yaml
  - path: cronjob/frontend-restart-warning-exp-disney.yaml
