apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          resources:
            requests:
              # pod リソース設定
              cpu: "2"
              memory: 4G
          env:
            # ---- 基本設定 ---- 
            - name: INIT_MEMORY
              value: 1G
            - name: MAX_MEMORY
              value: 4G            
            # ---- server configの変数 ---- 
            - name: ALLOW_NETHER
              value: "false"
            - name: DIFFICULTY
              value: peaceful
            - name: LEVEL_TYPE
              value: flat
            - name: CFG_ALLOW_END
              value: "false"
            # ---- plugins configの変数 ---- 
            # ---- plugins datebase ---- 
            - name: CFG_LUCKPERMS_SERVER_NAME
              value: disney
            # ---- discord SRV ---- 
            - name: CFG_DISCORDSRV_AUTH
              value: "true"
            - name: CFG_CFG_DISCORDSRV_ROLE_AUTH
              value: "true"
            - name: CFG_DISCORDSRV_ADMIN_USER
              value: haramiten
            - name: CFG_DISCORDSRV_LOG_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-disney
                  key: CFG_DISCORDSRV_LOG_CHANNEL_KEY
            - name: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mc-disney
                  key: CFG_DISCORDSRV_CONSOLE_CHANNEL_KEY
            # ------時間天候無効化コマンド ------
            - name: RCON_CMDS_STARTUP
              value: |-
                /time set day
                /weather clear
                /gamerule doDaylightCycle false
                /gamerule doWeatherCycle false
                /gamerule doMobSpawning false
                /gamerule spawn-npcs false
                /gamerule pvp false
          volumeMounts:
            # ------ nsfに格納されているmusic_worldのマウント ------
            # ------ worldデータ ------
            - name: world-data
              mountPath: /data/world
              subPath: world
            # ------plugins関連のマウント ------
            # ------ bluemap-world ------
            # worldのマウント
            - name: mc-plugin-bluemap-config
              mountPath: /config/plugins/BlueMap/maps/s1-world.conf
              subPath: bluemap-world.conf
      volumes:
        # worldデータの永続ストレージの指定
        - name: world-data
          persistentVolumeClaim:
            claimName: haramis-exp-disney-pvc
        # bluemap-worldデータの永続ストレージの指定
        - name: mc-plugin-bluemap-config
          configMap:
            name: mc-plugin-bluemap-config
