apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 172.0.0.0
  ports:
    - name: http-service
      port: 80
      targetPort: http
  selector:
    app: nginx
