apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 172.0.0.0
  ports:
    - name: http-service
      port: 80
      targetPort: http
    - name: https-service
      port: 443
      targetPort: https
  selector:
    app: nginx
