apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-whitelist-bot
spec:
  template:
    spec:
      containers:
        - name: bot
          env:
            - name: BOT_LANG
              value: en
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_BOTKEY
            - name: APPLY_CHANNEL
              value: "1456518809165889761"
            - name: APPROVE_CHANNEL
              value: "1456518866107629570"
            - name: ADMIN_ROLE
              value: "1454495091535118388"
            - name: BEDROCK_NAMESPACE
              value: debug
            - name: BEDROCK_POD
              value: mc-bedrock-0
            - name: BEDROCK_CONTAINER
              value: mc-bedrock
          volumeMounts:
            - name: whitelist-data2
              mountPath: /app/data
      volumes:
        - name: whitelist-data
          $patch: delete
        - name: whitelist-data2
          emptyDir: {}
