apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: debug
resources:
  # template
  - git::https://github.com/maron-gt123/jamming-minecraft-stream//sample/k8s?ref=develop

#patches:
#  - path: discordbot-deployment.yaml
