apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: debug
resources:
  # template
  - https://github.com/maron-gt123/jamming-minecraft-stream//sample/k8s?ref=main

patches:
  - path: config.yaml
