apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: debug
resources:
  # template
  - git::https://github.com/maron-gt123/bedrock-discord-whitelist//k8s?ref=main

  # lan環境下
  - http://nas.mcnet/k8s/debug/secret-discordbot.yaml
patches:
  - path: discordbot-deployment.yaml
