apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # deployment
  - ./deployment.yaml
  - ./lb-palworld.yaml
  - ./pvc-palworld.yaml
  # config & secret
  - ./config/config.yaml
  - ./config/secret-rcon.yaml
