apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld-server
  name: lb-palworld
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 53167
    protocol: UDP
    targetPort: server
  - name: query
    port: 27015
    protocol: UDP
    targetPort: query
  selector:
    app: palworld-server
  loadBalancerIP: 172.0.0.0
