apiVersion: v1
kind: ConfigMap
metadata:
  name: rcon-login-script
data:
  rcon-lobby-login.sh: |
    #!/bin/bash
    # 自動ログイン用 RCON スクリプト

    RCON_HOST="mc-service.mc-haramis-lobby.svc.cluster.local"
    RCON_PORT="25575"
    RCON_PASS=${CFG_MC_RCON_PASSWORD}

    /usr/local/bin/rcon-cli \
      --host $RCON_HOST \
      --port $RCON_PORT \
      --password $RCON_PASS \
      --interactive
  rcon-s1-login.sh: |
    #!/bin/bash
    # 自動ログイン用 RCON スクリプト

    RCON_HOST="mc-service.mc-haramis-s1.svc.cluster.local"
    RCON_PORT="25575"
    RCON_PASS=${CFG_MC_RCON_PASSWORD}

    /usr/local/bin/rcon-cli \
      --host $RCON_HOST \
      --port $RCON_PORT \
      --password $RCON_PASS \
      --interactive
