apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./statefulset.yaml

  # secret
  - ./config/secret-mcserver.yaml
  - ./config/secret-forwarding.yaml

  # plugins-config
  - ./plugins/config/prometheus-exporter-config.yaml
configMapGenerator:
- name: mc-plugins
  files:
    - plugins=plugins/common.txt
