apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./statefulset.yaml
  - ./service.yaml
  - ./service-metrics-patch.yaml
  # secret
  - ./config/secret-mcserver.yaml
  - ./config/secret-forwarding.yaml
  # cron-job
  - ./cronjob/restart-warning.yaml

  # config
  - ./config/paper-config.yaml
  - ./config/jmx-exporter-config.yaml
  # plugins-config
  - ./config/prometheus-exporter-config.yaml
  - ./config/serverbackup-config.yaml
