apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./statefulset.yaml

  # secret
  - ./config/secret-mcserver.yaml
  - ./../minecraft-proxy/config/secret-forwarding.yaml
configMapGenerator:
- name: mc-plugins
  files:
    - plugins=plugins/common.txt
