apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-uuidredirect-config
data:
  uuidredirect-config.json: |
    {
      "ebd6ed5c-7a32-49fd-b287-df57f2ffb33b": {
        "username": "",
        "server": "java"
      }
    }
