apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-uuidredirect-config
data:
  uuidredirect-config.json: |
    {
      "ebd6ed5c-7a32-49fd-b287-df57f2ffb33b": {
        "username": "maron_12345",
        "server": "java"
      }
      "ac27d02d-629e-4de2-8a46-90ed95a5cdf3": {
        "username": "nosukero",
        "server": "java"
      }
    }
