apiVersion: v1
kind: ConfigMap
metadata:
  name: discordbot-config
data:
  config.yaml: |
    bot:
      token: "DISCORD_BOT_TOKEN"
    
    server:
      name: bedrock_s1
      description: "自宅用統合版サーバー1"
      discord_guild: 123456789012345678
      apply_channel: 111111111111111111
      approve_channel: 222222222222222222
      admin_role: MC-Admin
    
      whitelist_file: "whitelist.json"
      allowlist_file: "allowlist.json"
    
      bds_reload: "kubectl exec -n mc-bedrock bedrock-s1-0 -- screen -S bedrock -X stuff 'allowlist reload\n'"
