apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-bedrock
spec:
  template:
    spec:
      containers:
        - name: mc-bedrock
          resources:
            requests:
              # pod リソース設定
              cpu: "2"
              memory: 4G
          env:
            - name: GAMEMODE
              value: survival
            - name: DIFFICULTY
              value: normal
        - name: discord-whitelist-bot
          image: marongt123/bedrock-discord-whitelist:latest
          imagePullPolicy: Always
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_BOTKEY
            - name: APPLY_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_APPLY_CHANNELID
            - name: APPROVE_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_APPROVE_CHANNELID
            - name: ADMIN_ROLE
              valueFrom:
                secretKeyRef:
                  name: secret-discordbot
                  key: DISCORD_ROLEID
            - name: BEDROCK_NAMESPACE
              value: mc-haramis
            - name: BEDROCK_POD
              value: mc-bedrock-0
          volumeMounts:
            - name: whitelist-data
              mountPath: /app/data
