apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-bedrock
spec:
  template:
    spec:
      containers:
        - name: mc-bedrock
          resources:
            requests:
              # pod リソース設定
              cpu: "2"
              memory: 4G
          env:
            - name: GAMEMODE
              value: survival
            - name: DIFFICULTY
              value: normal
