apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis
resources:
  # template
  - ../../templates/minecraft-bedrock
  # pv
  - ./pv-nfs-s1_world.yaml
  - ./pv-nfs-s1_whitelists.yaml
patches:
  - path: harami-statefulset.yaml
  - path: haramis-service-lb.yaml
