apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  web.conf: |
    server {
        listen 80 proxy_protocol;
        listen [::]:80 proxy_protocol;
        server_name _;
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl http2 proxy_protocol;
        listen [::]:443 ssl http2 proxy_protocol;
        server_name _;
        
        ssl_certificate     /etc/letsencrypt/live/haramiverse.f5.si/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/haramiverse.f5.si/privkey.pem;

        set_real_ip_from 0.0.0.0/0;
        real_ip_header proxy_protocol;

        root /usr/share/nginx/html;
        index index.html index.htm;
        
        location / {
            try_files $uri $uri/ =404;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
