apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis-rcon
resources:
  # template
  - ../../templates/mc-rcon
  # config
  - config/rcon-login.yaml
patches:
  - path: rcon-haramis-pod.yaml
