apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-rcon
spec:
  containers:
    - name: ubuntu
      volumeMounts:
        - name: mc-config
          mountPath: /home/ubuntu/
  volumes:
    - name: rcon-login
      configMap:
        name: rcon-login-script
