apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-rcon
spec:
  containers:
    - name: ubuntu
      env:
        - name: VELOCITY_RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mc-common
              key: VELOCITY_RCON_PASSWORD
        - name: CFG_MC_RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mc-common
              key: CFG_MC_RCON_PASSWORD
      volumeMounts:
        - name: rcon-login
          mountPath: /home/ubuntu/
  volumes:
    - name: rcon-login
      configMap:
        name: rcon-login-script
