apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-maroncloud-proxy
resources:
  # templates
  - ../../templates/minecraft-proxy
patches:
  - path: lb-service.yaml
  - path: patches-deployment.yaml
  - path: config/velocity-config.yaml
  - path: config/plugin-minimotd-config.yaml
  - path: config/plugin-UUIDRedirect-config.yaml
  - path: http://nas.mcnet/k8s/maroncloud-proxy/secret-velocity.yaml
