apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-haramis-proxy
resources:
  # templates
  - ../../templates/minecraft-proxy
  # secret
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-common.yaml
  - http://nas.mcnet/k8s/mc-haramis/secret-mc-dbaddress.yaml
patches:
  - path: lb-service.yaml
  - path: deployment-haramis.yaml
