apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-maroncloud-proxy
resources:
  # templates
  - ../../templates/minecraft-proxy
  # secret

patches:
  - path: lb-service.yaml
  - path: patches-deployment.yaml
