apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-jamming
resources:
  # template
  - ../../templates/minecraft-java
  # tiktok-live-mc-event-runner
  - git::https://github.com/maron-gt123/tiktok-live-mc-event-runner/k8s?ref=main
patches:
  - path: http://nas.mcnet/k8s/maroncloud-proxy/secret-velocity.yaml

  # tiktok-event-runner
  - path: event-runner/config.yaml
