apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-jamming
resources:
  # template
  - ../../templates/minecraft-java
patches:
  - path: http://nas.mcnet/k8s/maroncloud-proxy/secret-velocity.yaml
